# Generated by Django 4.1.7 on 2025-06-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paras', '0004_fackey_stukey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databook',
            name='Author',
            field=models.CharField(default='Prof. Gaurav Shrivastava', max_length=40),
        ),
        migrations.AlterField(
            model_name='databook',
            name='Subject',
            field=models.CharField(default='Network Security and Cryptography', max_length=80),
        ),
    ]
